--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCHOOL_STUDENTS
--------------------------------------------------------

  CREATE TABLE "HR"."SCHOOL_STUDENTS" 
   (	"STUDENT_NO" NUMBER(10,0), 
	"STUDENT_NAME" VARCHAR2(50 BYTE), 
	"GRADE" NUMBER(1,0), 
	"DEPARTMENT_NO" NUMBER(10,0), 
	"REGISTRATION_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.SCHOOL_STUDENTS
SET DEFINE OFF;
Insert into HR.SCHOOL_STUDENTS (STUDENT_NO,STUDENT_NAME,GRADE,DEPARTMENT_NO,REGISTRATION_DATE) values (10000,'정다훈',4,1001,to_date('20/05/02','RR/MM/DD'));
Insert into HR.SCHOOL_STUDENTS (STUDENT_NO,STUDENT_NAME,GRADE,DEPARTMENT_NO,REGISTRATION_DATE) values (10020,'홍길동',3,1000,to_date('20/05/03','RR/MM/DD'));
Insert into HR.SCHOOL_STUDENTS (STUDENT_NO,STUDENT_NAME,GRADE,DEPARTMENT_NO,REGISTRATION_DATE) values (10021,'강감찬',2,1000,to_date('20/05/03','RR/MM/DD'));
Insert into HR.SCHOOL_STUDENTS (STUDENT_NO,STUDENT_NAME,GRADE,DEPARTMENT_NO,REGISTRATION_DATE) values (10022,'김유신',1,1001,to_date('20/05/03','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007008
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007008" ON "HR"."SCHOOL_STUDENTS" ("STUDENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SCHOOL_STUDENTS
--------------------------------------------------------

  ALTER TABLE "HR"."SCHOOL_STUDENTS" ADD PRIMARY KEY ("STUDENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SCHOOL_STUDENTS" ADD CHECK (GRADE IN (1,2,3,4)) ENABLE;
  ALTER TABLE "HR"."SCHOOL_STUDENTS" MODIFY ("REGISTRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."SCHOOL_STUDENTS" MODIFY ("STUDENT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SCHOOL_STUDENTS
--------------------------------------------------------

  ALTER TABLE "HR"."SCHOOL_STUDENTS" ADD FOREIGN KEY ("DEPARTMENT_NO")
	  REFERENCES "HR"."SCHOOL_DEPARTMENTS" ("DEPARTMENT_NO") ENABLE;
