--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCHOOL_PROFESSORS
--------------------------------------------------------

  CREATE TABLE "HR"."SCHOOL_PROFESSORS" 
   (	"PROFESSOR_NO" NUMBER(10,0), 
	"PROFESSOR_NAME" VARCHAR2(50 BYTE), 
	"DEPARTMENT_NO" NUMBER(10,0), 
	"PROFESSOR_POSITION" VARCHAR2(50 BYTE), 
	"REGISTRATION_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.SCHOOL_PROFESSORS
SET DEFINE OFF;
Insert into HR.SCHOOL_PROFESSORS (PROFESSOR_NO,PROFESSOR_NAME,DEPARTMENT_NO,PROFESSOR_POSITION,REGISTRATION_DATE) values (1,'김교수',1001,'정교수',to_date('20/05/02','RR/MM/DD'));
Insert into HR.SCHOOL_PROFESSORS (PROFESSOR_NO,PROFESSOR_NAME,DEPARTMENT_NO,PROFESSOR_POSITION,REGISTRATION_DATE) values (21,'강교수',1000,'정교수',to_date('20/05/03','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007003
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007003" ON "HR"."SCHOOL_PROFESSORS" ("PROFESSOR_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SCHOOL_PROFESSORS
--------------------------------------------------------

  ALTER TABLE "HR"."SCHOOL_PROFESSORS" ADD PRIMARY KEY ("PROFESSOR_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SCHOOL_PROFESSORS" MODIFY ("REGISTRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."SCHOOL_PROFESSORS" MODIFY ("PROFESSOR_POSITION" NOT NULL ENABLE);
  ALTER TABLE "HR"."SCHOOL_PROFESSORS" MODIFY ("DEPARTMENT_NO" NOT NULL ENABLE);
  ALTER TABLE "HR"."SCHOOL_PROFESSORS" MODIFY ("PROFESSOR_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SCHOOL_PROFESSORS
--------------------------------------------------------

  ALTER TABLE "HR"."SCHOOL_PROFESSORS" ADD FOREIGN KEY ("DEPARTMENT_NO")
	  REFERENCES "HR"."SCHOOL_DEPARTMENTS" ("DEPARTMENT_NO") ENABLE;
